package presentation.forms.member;

import com.*;
import contract.dto.IMemberDto;
import contract.useCaseController.ISearchChangeMember;
import java.util.List;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import presentation.basics.*;

/**
 @author Lucia
 */
public class SearchMemberForm
        extends AbstractMainForm
{
    private boolean dataExists;
//    private boolean adminPermission;
    ServiceClient client;
    ISearchChangeMember controller;
    IMemberDto user;
    // List<IRoleDto> roles;
    //IAddressDto address;
    // ICountryDto country;
    //  IClubTeamDto clubTeam;
    // private List<ITypeOfSportDto> typeOfSports;
//    private List<ITypeOfSportDto> availableSports;
//    private List<ITypeOfSportDto> selectedSports = new LinkedList<>();
//    private List<IClubTeamDto> selectedTrainerTeams;
//    private List<IClubTeamDto> selectedPlayerTeams;
    private List<IMemberDto> matchingMembers;

    /**
     Creates new form SearchMemb
     */
    public SearchMemberForm(AbstractForm form, ServiceClient client, IMemberDto user)
            throws ServiceNotAvailableException
    {
        super(form);
        this.client = client;
        this.user = user;
        controller = this.client.getSearchChangeMemberService();
        initComponents();

        personDataPanel1.setController(this.client.getAddressService());
        membershipDataPanel2.setController(this.client.getMembershipService());
        //availableSports = controller.getTypeOfSports();
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        paneSearch = new javax.swing.JPanel();
        txtfieldSearchMemb = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMember = new javax.swing.JTable();
        btnApplyChange = new javax.swing.JButton();
        membershipDataPanel2 = new presentation.forms.member.MembershipDataPanel();
        personDataPanel1 = new presentation.forms.member.PersonDataPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(848, 549));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchActionPerformed(evt);
            }
        });

        tabMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Membership Nr.", "First Name", "Last Name", "Birth Date", "Gender"
            }
        ));
        tabMember.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent e)
            {
                tableMemberValueChanged(e);
            }
        });
        jScrollPane1.setViewportView(tabMember);

        btnApplyChange.setText("Apply Changes");
        btnApplyChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnApplyChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneSearchLayout = new javax.swing.GroupLayout(paneSearch);
        paneSearch.setLayout(paneSearchLayout);
        paneSearchLayout.setHorizontalGroup(
            paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchLayout.createSequentialGroup()
                .addGroup(paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                            .addGroup(paneSearchLayout.createSequentialGroup()
                                .addComponent(txtfieldSearchMemb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(personDataPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(membershipDataPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(paneSearchLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(btnApplyChange, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneSearchLayout.setVerticalGroup(
            paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldSearchMemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personDataPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(membershipDataPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApplyChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtfieldSearchMemb.getText() == null)
        {
            JOptionPane.showMessageDialog(parent, "Please enter a name!");
        }
        else
        {
            try
            {
                matchingMembers = controller.getMatchingMembers(txtfieldSearchMemb.getText());

                TableModel tm = tabMember.getModel();

                DefaultTableModel dm = (DefaultTableModel) tabMember.getModel();
                dm.setRowCount(0);
                dm.setRowCount(matchingMembers.size());

                tabMember.setModel(tm);
                TableModel tableModel = tabMember.getModel();
                for (int row = 0;
                     row < matchingMembers.size();
                     row++)
                {
                    IMemberDto tmpMember = matchingMembers.get(row);

                    tableModel.setValueAt(tmpMember.getId().toString(), row, 0);
                    tableModel.setValueAt(tmpMember.getPrename(), row, 1);
                    tableModel.setValueAt(tmpMember.getLastname(), row, 2);
                    tableModel.setValueAt(tmpMember.getDateOfBirth().toString(), row, 3);
                    tableModel.setValueAt(tmpMember.getGender() ? "female" : "male", row, 4);
                }

                tabMember.setModel(tableModel);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(parent, "Your entry ' " + txtfieldSearchMemb.getText() + "' could not be found!");
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnApplyChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnApplyChangeActionPerformed
    {//GEN-HEADEREND:event_btnApplyChangeActionPerformed
        save();
            //TODO: Throw exception in case of an error !!!!!        
    }//GEN-LAST:event_btnApplyChangeActionPerformed

    private void tableMemberValueChanged(ListSelectionEvent e)
    {
        IMemberDto member = matchingMembers.get(tabMember.getSelectedRow());

        personDataPanel1.setMember(member);
        membershipDataPanel2.setMember(member);
    }

    //  private void btnAddSportActionPerformed(java.awt.event.ActionEvent evt)
    //  {
//        try
//        {
//            if (radioTrainer.isSelected() || radioPlayer.isSelected())
//            {
//                //open new frame which enables selection of more sports
//                new SelectSportsHelper(availableSports, selectedSports, this);
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "Member is no player or trainer!");
//            }
//        }
//        catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, "Service currently not available. Sorry!");
//        }
//    }
    // private void btnTeamsActionPerformed(java.awt.event.ActionEvent evt)
    //  {
//        try
//        {
//            new SelectTeamsHelper(selectedSports, this, false);
//        }
//        catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, "Service currently not available. Sorry!");
//        }
//    }
//
//    public void setTxtFieldSports(List<ITypeOfSportDto> selection)
//    {
//        if (selection.isEmpty())
//        {
//            txtFieldSports.setText("");
//            return;
//        }
//
//        this.selectedSports = selection;
//
//        StringBuilder sb = new StringBuilder(selectedSports.size());
//        for (ITypeOfSportDto s : selectedSports)
//        {
//            sb.append(s);
//            sb.append(", ");
//        }
//
//        txtFieldSports.setText(sb.toString().substring(sb.length() - 2, sb.length()));
    //  }
//    private void updateDetailPane()
//    {
//        dataExists = true;
//
//        IMemberDto selectedMember = controller.getSelectedMember();
//
//
//        txtfieldMemberNr.setText(member.getId().toString());
//        dateEntry.setDate(member.getMemberFrom());
//    }
    private void save()
    {
        IMemberDto selectedMember = personDataPanel1.getMember();
        IMemberDto anotherSelectedMember = membershipDataPanel2.getMember();

        selectedMember.setMemberFrom(anotherSelectedMember.getMemberFrom());
        // Wird vielleicht mal benötigt selectedMember.setMemberTo(anotherSelectedMember.getMemberTo());
        selectedMember.setRoleList(anotherSelectedMember.getRoleList());

        controller.setNewMember(selectedMember, personDataPanel1.getAddress());
    }

//    public List<IClubTeamDto> getClubTeams(ITypeOfSportDto sport)
//    {
//        return controller.getClubTeamsByTypeOfSport(sport);
//    }
    public JPanel getPanel()
    {
        return paneSearch;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyChange;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private presentation.forms.member.MembershipDataPanel membershipDataPanel2;
    private javax.swing.JPanel paneSearch;
    private presentation.forms.member.PersonDataPanel personDataPanel1;
    private javax.swing.JTable tabMember;
    private javax.swing.JTextField txtfieldSearchMemb;
    // End of variables declaration//GEN-END:variables
}
