/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.forms.member;

import contract.dto.*;
import contract.dto.classes.MemberDto;
import contract.useCaseController.*;
import java.awt.event.ActionEvent;

/**
 @author Thomas
 */
public class PersonDataPanel
        extends javax.swing.JPanel
{
    private IMemberDto member;
    private IAddressController controller;

    public void setController(IAddressController controller)
    {
        this.controller = controller;
        addressPanel1.setController(controller);
    }

    public IMemberDto getMember()
    {
        if (member == null)
        {
            member = new MemberDto();
        }

        member.setPrename(txtfieldFName.getText());
        member.setLastname(txtfieldLName.getText());
        member.setDateOfBirth(dateBirthday.getDate());
        member.setTelephonenumber(txtfieldPhone.getText());
        member.setEmailAddress(txtfieldMail.getText());

        member.setGender(radioFemale.isSelected());
        member.setNationality(controller.getCountryByName(txtfieldNationality.getText()).getId());

        return member;
    }

    public void setMember(IMemberDto member)
    {
        this.member = member;

        txtfieldFName.setText(member.getPrename());
        txtfieldLName.setText(member.getLastname());
        dateBirthday.setDate(member.getDateOfBirth());
        txtfieldPhone.setText(member.getTelephonenumber());
        txtfieldMail.setText(member.getEmailAddress());

        radioFemale.setSelected(member.getGender());
        radioMale.setSelected(!member.getGender());

        ICountryDto c = controller.getCountryById(member.getNationality());
        String countryName = c + "";
        txtfieldNationality.setText(countryName);
        
        this.addressPanel1.setAddress(controller.getById(member.getAddress()));
    }

    public IAddressDto getAddress()
    {
        return addressPanel1.getAddress();
    }

    /**
     Creates new form PersonDataPanel
     */
    public PersonDataPanel()
    {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        dateBirthday = new com.toedter.calendar.JDateChooser();
        lblGender = new javax.swing.JLabel();
        radioFemale = new javax.swing.JRadioButton();
        radioMale = new javax.swing.JRadioButton();
        txtfieldPhone = new javax.swing.JTextField();
        txtfieldMail = new javax.swing.JTextField();
        txtfieldLName = new javax.swing.JTextField();
        txtfieldFName = new javax.swing.JTextField();
        lblPhone1 = new javax.swing.JLabel();
        txtfieldNationality = new javax.swing.JTextField();
        addressPanel1 = new presentation.forms.member.AddressPanel();

        lblFName.setText("First Name");

        lblLName.setText("Last Name");

        lblMail.setText("Mail");

        lblPhone.setText("Phone");

        lblBirthDate.setText("Birth Date");

        lblGender.setText("Gender");

        radioFemale.setText("female");
        radioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemaleActionPerformed(evt);
            }
        });
        radioFemale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                radioFemalePropertyChange(evt);
            }
        });

        radioMale.setText("male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        radioMale.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                radioMalePropertyChange(evt);
            }
        });

        txtfieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldMailActionPerformed(evt);
            }
        });

        lblPhone1.setText("Nationality");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFName)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender)
                            .addComponent(lblPhone1)
                            .addComponent(lblBirthDate)
                            .addComponent(lblPhone)
                            .addComponent(lblMail)
                            .addComponent(lblLName))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfieldFName)
                    .addComponent(txtfieldLName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfieldMail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfieldPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateBirthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtfieldNationality, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(radioFemale)
                        .addGap(18, 18, 18)
                        .addComponent(radioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addressPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName)
                            .addComponent(txtfieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMail))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthDate)))
                    .addComponent(addressPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioFemale)
                            .addComponent(radioMale))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone1)
                    .addComponent(txtfieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioFemaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioFemaleActionPerformed
    {//GEN-HEADEREND:event_radioFemaleActionPerformed
        genderActionPerformed(evt);
    }//GEN-LAST:event_radioFemaleActionPerformed

    private void radioFemalePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_radioFemalePropertyChange
    {//GEN-HEADEREND:event_radioFemalePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFemalePropertyChange

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_radioMaleActionPerformed
    {//GEN-HEADEREND:event_radioMaleActionPerformed
        genderActionPerformed(evt);
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radioMalePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_radioMalePropertyChange
    {//GEN-HEADEREND:event_radioMalePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMalePropertyChange

    private void txtfieldMailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtfieldMailActionPerformed
    {//GEN-HEADEREND:event_txtfieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldMailActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentation.forms.member.AddressPanel addressPanel1;
    private com.toedter.calendar.JDateChooser dateBirthday;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JTextField txtfieldFName;
    private javax.swing.JTextField txtfieldLName;
    private javax.swing.JTextField txtfieldMail;
    private javax.swing.JTextField txtfieldNationality;
    private javax.swing.JTextField txtfieldPhone;
    // End of variables declaration//GEN-END:variables

    private void genderActionPerformed(ActionEvent evt)
    {
        if (evt.getSource() == radioFemale)
        {
            radioMale.setEnabled(!radioFemale.isSelected());
        }
        else
        {
            radioFemale.setEnabled(!radioMale.isSelected());
        }
    }
}
