package presentation.forms.competition;

import com.contract.IUseCaseControllerFactory;
import com.ServiceNotAvailableException;
import contract.dto.*;
import contract.useCaseController.IShowCompetitionController;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.*;
import javax.swing.table.*;
import presentation.basics.*;

/**

 @author Lucia
 */
public class ShowCompetitionForm
        extends AbstractMainForm
{
    IUseCaseControllerFactory client;
    IShowCompetitionController controller;
    ICompetitionDto competition;
    List<IClubTeamDto> clubTeams = new LinkedList<IClubTeamDto>();
    List<IMatchDto> compMatches= new LinkedList<IMatchDto>();
    IClubTeamDto cTeam;
    IMemberDto user;

    /**
     Creates new form ShowMatchInfo
     */
    public ShowCompetitionForm(AbstractForm form, IUseCaseControllerFactory client, IMemberDto user)
            throws ServiceNotAvailableException
    {
        super(form);
        this.client = client;
        this.user = user;
        controller = this.client.getShowCompetitionController();
        initComponents();
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        paneShowCompetition = new javax.swing.JPanel();
        comboCompetition = new javax.swing.JComboBox();
        lblCompetition = new javax.swing.JLabel();
        scrollCompetition = new javax.swing.JScrollPane();
        tableCompetition = new javax.swing.JTable();
        lblYourMembers = new javax.swing.JLabel();
        scrollMembers = new javax.swing.JScrollPane();
        tableOurMembers = new javax.swing.JTable();
        showBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(848, 549));

        comboCompetition.setModel(new javax.swing.DefaultComboBoxModel(getCompetitions()));
        comboCompetition.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboCompetitionActionPerformed(evt);
            }
        });

        lblCompetition.setText("Competition");

        tableCompetition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Team A", "Team B", "Result"
            }
        ));
        tableCompetition.getSelectionModel().addListSelectionListener(new ListSelectionListener()
        {
            public void valueChanged(ListSelectionEvent e)
            {
                tableCompetitionValueChanged(e);
            }
        });
        scrollCompetition.setViewportView(tableCompetition);

        lblYourMembers.setText("Announced members from your department");

        tableOurMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "First Name", "Last Name"
            }
        ));
        scrollMembers.setViewportView(tableOurMembers);

        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                showBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneShowCompetitionLayout = new javax.swing.GroupLayout(paneShowCompetition);
        paneShowCompetition.setLayout(paneShowCompetitionLayout);
        paneShowCompetitionLayout.setHorizontalGroup(
            paneShowCompetitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneShowCompetitionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneShowCompetitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addGroup(paneShowCompetitionLayout.createSequentialGroup()
                        .addGroup(paneShowCompetitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneShowCompetitionLayout.createSequentialGroup()
                                .addComponent(lblCompetition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showBtn))
                            .addComponent(lblYourMembers))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneShowCompetitionLayout.setVerticalGroup(
            paneShowCompetitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneShowCompetitionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneShowCompetitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompetition)
                    .addComponent(showBtn))
                .addGap(18, 18, 18)
                .addComponent(scrollCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblYourMembers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneShowCompetition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneShowCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCompetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCompetitionActionPerformed
        competition = (ICompetitionDto) comboCompetition.getSelectedItem(); //set competition new
        compMatches = controller.getMatchs(competition.getMatchList());     //competitions matches

        if (competition != null)
        {
            setNewCompTable();
        }
    }//GEN-LAST:event_comboCompetitionActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showBtnActionPerformed
    {//GEN-HEADEREND:event_showBtnActionPerformed
        competition = (ICompetitionDto) comboCompetition.getSelectedItem(); //set competition new
        compMatches = controller.getMatchs(competition.getMatchList());     //competitions matches

        if (competition != null)
        {
            setNewCompTable();
        }
    }//GEN-LAST:event_showBtnActionPerformed

    private Object[] getCompetitions()
    {
        if (controller.getCompetitions() != null)
        {
            List<ICompetitionDto> compDtos = controller.getCompetitions();
            return compDtos.toArray();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "There are currently no competitions!");
            return new Object[0];
        }
    }

    private void setNewCompTable()
    {
        TableModel tm = tableCompetition.getModel();

        DefaultTableModel dm = (DefaultTableModel) tableCompetition.getModel();
        dm.setRowCount(0);
        dm.setRowCount(compMatches.size());

        tableCompetition.setModel(tm);
        TableModel tableModel = tableCompetition.getModel();

        for (int row = 0; row < compMatches.size(); row++)
        {
            int i = 0;
            IMatchDto tmp = compMatches.get(row);     //get next match from list

            tableModel.setValueAt(controller.getTeam(tmp.getHometeam()).getName(), row, 0);
            tableModel.setValueAt(controller.getTeam(tmp.getForeignteam()).getName(), row, 1);

            IMatchresultDto result = controller.getMatchresult(tmp.getMatchresult());
            tableModel.setValueAt(result.getPointsHometeam() + " : " + result.getPointsForeignteam(), row, 2);
        }
        tableCompetition.setModel(tableModel);
    }

    private void tableCompetitionValueChanged(ListSelectionEvent e)
    {
        final int row = tableCompetition.getSelectedRow();
        IMatchDto match = compMatches.get(row);

        setNewMembersTable(match);
    }

    private void setNewMembersTable(IMatchDto match)
    {
        findClubTeams();    //build up list with club teams

        //check if selected match contains relevant clubteam
        if (containsClubTeam(match) == true) {
            List<IPlayerDto> tmpPlayer = controller.getPlayer(cTeam);
            
            TableModel tm = tableOurMembers.getModel();
            DefaultTableModel dm = (DefaultTableModel) tableOurMembers.getModel();
            dm.setRowCount(0);
            dm.setRowCount(tmpPlayer.size());

            tableOurMembers.setModel(tm);
            TableModel tableModel = tableOurMembers.getModel();

            for (int row = 0; row < tmpPlayer.size(); row++) {
                String[] fullname = tmpPlayer.get(row).toString().split(" ");
                tableModel.setValueAt(fullname[0], row, 0);   // first name
                tableModel.setValueAt(fullname[1], row, 1);     // last name
            }
            
            tableOurMembers.setModel(tableModel);
        }        
    }

    private void findClubTeams()
    {
        clubTeams.clear();

        for (IMatchDto m : compMatches)
        {
            IClubTeamDto fteam = controller.getClubTeam(m.getForeignteam());

            if (fteam != null)
            {
                clubTeams.add(fteam);
            }

            IClubTeamDto hteam = controller.getClubTeam(m.getHometeam());

            if (hteam != null)
            {
                clubTeams.add(hteam);
            }
        }
    }

    private boolean containsClubTeam(IMatchDto match)
    {
        for (IClubTeamDto ct : clubTeams)
        {
            Integer id = ct.getId();
            if (id.equals(match.getHometeam())) {
                cTeam = ct;
                return true;
            } else if (id.equals(match.getForeignteam())) {
                cTeam = ct;
                return true;
            }
        }
        return false;
    }

    public JPanel getPanel()
    {
        return paneShowCompetition;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCompetition;
    private javax.swing.JLabel lblCompetition;
    private javax.swing.JLabel lblYourMembers;
    private javax.swing.JPanel paneShowCompetition;
    private javax.swing.JScrollPane scrollCompetition;
    private javax.swing.JScrollPane scrollMembers;
    private javax.swing.JButton showBtn;
    private javax.swing.JTable tableCompetition;
    private javax.swing.JTable tableOurMembers;
    // End of variables declaration//GEN-END:variables
}
